INSERT INTO estados (id, nome) VALUES (01, 'Acre');
INSERT INTO estados (id, nome) VALUES (02, 'Alagoas');
INSERT INTO estados (id, nome) VALUES (03, 'Amapá');
INSERT INTO estados (id, nome) VALUES (04, 'Amazonas');
INSERT INTO estados (id, nome) VALUES (05, 'Bahia');
INSERT INTO estados (id, nome) VALUES (06, 'Ceará');
INSERT INTO estados (id, nome) VALUES (07, 'Distrito Federal');
INSERT INTO estados (id, nome) VALUES (08, 'Espírito Santo');
INSERT INTO estados (id, nome) VALUES (09, 'Goiás');
INSERT INTO estados (id, nome) VALUES (10, 'Maranhão');
INSERT INTO estados (id, nome) VALUES (11, 'Mato Grosso');
INSERT INTO estados (id, nome) VALUES (12, 'Mato Grosso do Sul');
INSERT INTO estados (id, nome) VALUES (13, 'Minas Gerais');
INSERT INTO estados (id, nome) VALUES (14, 'Pará');
INSERT INTO estados (id, nome) VALUES (15, 'Paraíba');
INSERT INTO estados (id, nome) VALUES (16, 'Paraná');
INSERT INTO estados (id, nome) VALUES (17, 'Pernambuco');
INSERT INTO estados (id, nome) VALUES (18, 'Piauí');
INSERT INTO estados (id, nome) VALUES (19, 'Rio de Janeiro');
INSERT INTO estados (id, nome) VALUES (20, 'Rio Grande do Norte');
INSERT INTO estados (id, nome) VALUES (21, 'Rio Grande do Sul');
INSERT INTO estados (id, nome) VALUES (22, 'Rondônia');
INSERT INTO estados (id, nome) VALUES (23, 'Roraima');
INSERT INTO estados (id, nome) VALUES (24, 'Santa Catarina');
INSERT INTO estados (id, nome) VALUES (25, 'São Paulo');
INSERT INTO estados (id, nome) VALUES (26, 'Sergipe');
INSERT INTO estados (id, nome) VALUES (27, 'Tocantins');